#define COOKIE_REQUEST_ID 0
#define CLIENTBOUND_PLUGIN_MESSAGE_CONFIGURATION_ID (COOKIE_REQUEST_ID+1)
#define DISCONNECT_CONFIGURATION_ID (CLIENTBOUND_PLUGIN_MESSAGE_CONFIGURATION_ID+1)
#define FINISH_CONFIGURATION_ID (DISCONNECT_CONFIGURATION_ID+1)
#define CLIENTBOUND_KEEPALIVE_CONFIGURATION_ID (FINISH_CONFIGURATION_ID+1)
#define PING_CONFIGURATION_ID (CLIENTBOUND_KEEPALIVE_CONFIGURATION_ID+1)
#define RESET_CHAT_ID (PING_CONFIGURATION_ID+1)
#define REGISTRY_DATA_ID (RESET_CHAT_ID+1)
#define REMOVE_RESOURCE_PACK_CONFIGURATION_ID (REGISTRY_DATA_ID+1)
#define ADD_RESOURCE_PACK_CONFIGURATION_ID (REMOVE_RESOURCE_PACK_CONFIGURATION_ID+1)
#define STORE_COOKIE_CONFIGURATION_ID (ADD_RESOURCE_PACK_CONFIGURATION_ID+1)
#define TRANSFER_CONFIGURATION_ID (STORE_COOKIE_CONFIGURATION_ID+1)
#define FEATURE_FLAGS_ID (TRANSFER_CONFIGURATION_ID+1)
#define UPDATE_TAGS_ID (FEATURE_FLAGS_ID+1)
#define CLIENTBOUND_KNOWN_PACKS_ID (UPDATE_TAGS_ID+1)
#define CUSTOM_REPORT_DETAILS_CONFIGURATION_ID (CLIENTBOUND_KNOWN_PACKS_ID+1)
#define SERVER_LINKS_CONFIGURATION_ID (CUSTOM_REPORT_DETAILS_CONFIGURATION_ID+1)
#define CLEAR_DIALOG_CONFIGURATION_ID (SERVER_LINKS_CONFIGURATION_ID+1)
#define SHOW_DIALOG_CONFIGURATION_ID (CLEAR_DIALOG_CONFIGURATION_ID+1)


PACKET(clientbound_known_packs,
       RL(known_pack, known_pack, packs, num_packs);
       );


PACKET(finish_configuration,
       );

//
PACKET(registry_data_entry,
       R(var_str, lstr, entry_id);
       O(network_nbt, nbt_tag_t*, data);
       );
PACKET(registry_data,
       R(var_str, lstr, registry_id);
       RL(registry_data_entry, registry_data_entry, entries, num_entries);
       );
