#define CONFIRM_TELEPORTATION_ID 0
#define QUERY_BLOCK_ENTITY_TAG_ID (CONFIRM_TELEPORTATION_ID+1)
#define BUNDLE_ITEM_SELECTED_ID (QUERY_BLOCK_ENTITY_TAG_ID+1)
#define CHANGE_DIFFUCULTY_ID (BUNDLE_ITEM_SELECTED_ID+1)
#define CHANGE_GAME_MODE_ID (CHANGE_DIFFUCULTY_ID+1)
#define ACK_MESSAGE_ID (CHANGE_GAME_MODE_ID+1)
#define CHAT_COMMAND_ID (ACK_MESSAGE_ID+1)
#define SIGNED_CHAT_COMMAND_ID (CHAT_COMMAND_ID+1)
#define CHAT_MESSAGE_ID (SIGNED_CHAT_COMMAND_ID+1)
#define PLAYER_SESSION_ID (CHAT_MESSAGE_ID+1)
#define CHUNK_BATCH_RECIEVED_ID (PLAYER_SESSION_ID+1)
#define CLIENT_STATUS_ID (CHUNK_BATCH_RECIEVED_ID+1)
#define CLIENT_TICK_END_ID (CLIENT_STATUS_ID+1)
#define CLIENT_INFORMATION_PLAY_ID (CLIENT_TICK_END_ID+1)
#define COMMAND_SUGGESTIONS_REQUEST_ID (CLIENT_INFORMATION_PLAY_ID+1)
#define ACK_CONFIGURATION_ID (COMMAND_SUGGESTIONS_REQUEST_ID+1)
#define CLICK_CONTAINER_BUTTON_PLAY_ID (ACK_CONFIGURATION_ID+1)
#define CLICK_CONTAINER_PLAY_ID (CLICK_CONTAINER_BUTTON_PLAY_ID+1)
#define CLOSE_CONTAINER_PLAY_ID (CLICK_CONTAINER_PLAY_ID+1)
#define CHANGE_CONTAINER_SLOT_STATE_ID (CLOSE_CONTAINER_PLAY_ID+1)
#define COOKIE_RESPONSE_PLAY_ID (CHANGE_CONTAINER_SLOT_STATE_ID+1)
#define SERVERBOUND_PLUGIN_MESSAGE_PLAY_ID (COOKIE_RESPONSE_PLAY_ID+1)
#define DEBUG_SAMPLE_SUBSCRIPTION_ID (SERVERBOUND_PLUGIN_MESSAGE_PLAY_ID+1)
#define EDIT_BOOK_ID (DEBUG_SAMPLE_SUBSCRIPTION_ID+1)
#define QUERY_ENTITY_TAG_ID (EDIT_BOOK_ID+1)
#define INTERACT_ID (QUERY_ENTITY_TAG_ID+1)
#define JIGSAW_GENERATE_ID (INTERACT_ID+1)
#define SERVERBOUND_KEEP_ALIVE_ID (JIGSAW_GENERATE_ID+1)
#define LOCK_DIFFUCULTY_ID (SERVERBOUND_KEEP_ALIVE_ID+1)
#define SET_PLAYER_POSITION_ID (LOCK_DIFFUCULTY_ID+1)
#define SET_PLAYER_POSITION_AND_ROTATION_ID (SET_PLAYER_POSITION_ID+1)
#define SET_PLAYER_ROTATION_ID (SET_PLAYER_POSITION_AND_ROTATION_ID+1)
#define SET_PLAYER_MOVEMENT_FLAGS_ID (SET_PLAYER_ROTATION_ID+1)
#define MOVE_VEHICLE_SERVERBOUND_ID (SET_PLAYER_MOVEMENT_FLAGS_ID+1)
#define PADDLE_BOAT_ID (MOVE_VEHICLE_SERVERBOUND_ID+1)
#define PICK_ITEM_FROM_BLOCK_ID (PADDLE_BOAT_ID+1)
#define PICK_ITEM_FROM_ENTITY_ID (PICK_ITEM_FROM_BLOCK_ID+1)
#define PING_REQUEST_PLAY_ID (PICK_ITEM_FROM_ENTITY_ID+1)
#define PLACE_RECIPE_ID (PING_REQUEST_FROM_PLAY_ID+1)
#define PLAYER_ABILITIES_SERVERBOUND_ID (PLACE_RECIPE_ID+1)
#define PLAYER_ACTION_ID (PLAYER_ABILITIES_SERVERBOUND_ID+1)
#define PLAYER_COMMAND_ID (PLAYER_ACTION_ID+1)
#define PLAYER_INPUT_ID (PLAYER_COMMAND_ID+1)
#define PLAYER_LOADED_ID (PLAYER_INPUT_ID+1)
#define PONG_PLAY_ID (PLAYER_LOADED_ID+1)
#define CHANGE_RECIPIE_BOOK_SETTINGS_ID (PONG_PLAY_ID+1)
#define SET_SEEN_RECIPE_ID (CHANGE_RECIPIE_BOOK_SETTINGS_ID+1)
#define RENAME_ITEM_ID (SET_SEEN_RECIPE_ID+1)
#define RESOURCE_PACK_RESPONSE_PLAY_ID (RENAME_ITEM_ID+1)
#define SEEN_ADVANCEMENTS_ID (RESOURCE_PACK_RESPONSE_PLAY_ID+1)
#define SELECT_TRADE_ID (SEEN_ADVANCEMENTS_ID+1)
#define SET_BEACON_EFFECT_ID (SELECT_TRADE_ID+1)
#define SET_HELD_ITEM_SERVERBOUND_ID (SET_BEACON_EFFECT_ID+1)
#define PROGRAM_COMMAND_BLOCK_ID (SET_HELD_ITEM_SERVERBOUND_ID+1)
#define PROGRAM_COMMAND_BLOCK_MINECART_ID (PROGRAM_COMMAND_BLOCK_ID+1)
#define SET_CREATIVE_MODE_SLOT_ID (PROGRAM_COMMAND_BLOCK_MINECART_ID+1)
#define PROGRAM_JIGSAW_BLOCK_ID (SET_CREATIVE_MODE_SLOT_ID+1)
#define PROGRAM_STRUCTURE_BLOCK_ID (PROGRAM_JIGSAW_BLOCK_ID+1)
#define SET_TEST_BLOCK_ID (PROGRAM_STRUCTURE_BLOCK_ID+1)
#define UPDATE_SIGN_ID (SET_TEST_BLOCK_ID+1)
#define SWING_ARM_ID (UPDATE_SIGN_ID+1)
#define TELEPORT_TO_ENTITY_ID (SWING_ARM_ID+1)
#define TEST_INSTANCE_BLOCK_ACTION_ID (TELEPORT_TO_ENTITY_ID+1)
#define USE_ITEM_ON_ID (TEST_INSTANCE_BLOCK_ACTION_ID+1)
#define USE_ITEM_ID (USE_ITEM_ON_ID+1)
#define CUSTOM_CLICK_ACTION_ID (USE_ITEM_ID+1)


PACKET(confirm_teleportation,
       R(var_int, int32_t, teleport_id);
       );

PACKET(set_player_position,
       R(double, double, x);
       R(double, double, y);
       R(double, double, z);
       R(byte, int8_t, flags);
       );
PACKET(set_player_position_and_rotation,
       R(double, double, x);
       R(double, double, y);
       R(double, double, z);
       R(float, float, yaw);
       R(float, float, pitch);
       R(byte, int8_t, flags);
       );

PACKET(set_player_rotation,
       R(float, float, yaw);
       R(float, float, pitch);
       R(byte, int8_t, flags);
       );
